### ISSUE TITLE
Как запустить приложение?

### ISSUE THREAD

**Issue by GorgeousPuree** [detlassnake/ntuDP-ratingCalculator#1]
Для того чтобы пользователь смог запустить приложение, ему необходимо скомпилировать исходный код.
Возможно стоит как-то **автоматизировать** этот процесс, чтобы пользователь мог использовать приложение с коробки? 
После этого можно сделать релиз.

**Comment by detlassnake** [comment]
Привет, к ссылке на этот проект прилагался архив с .exe файлом для запуска.

> Для того чтобы пользователь смог запустить приложение, ему необходимо скомпилировать исходный код.
> Возможно стоит как-то **автоматизировать** этот процесс, чтобы пользователь мог использовать приложение с коробки?
> После этого можно сделать релиз.

**Comment by GorgeousPuree** [comment]
> к ссылке

Я понял, но если человек просто наткнется на этот репозиторий, то ему будет непонятно, где .exe взять.

**Comment by detlassnake** [comment]
Данное приложение очень узкоспециально потому что актуально только студентов НТУ "ДП". Ну а на случай если кто-то на него наткнется то я могу предположить что человек сможет без проблем поднять у себя проект. Здесь не магазин приложений, а распределённая система управления версиями. Если есть какие-нибудь советы или идеи можешь написать мне в telegram обсудим.


>если человек просто наткнется на этот репозиторий, то ему будет непонятно, где .exe взять.
